/**:
    ros__parameters:
        feature_extract_enable: false
        point_filter_num: 4
        max_iteration: 3
        filter_size_surf: 0.5
        filter_size_map: 0.5
        cube_side_length: 1000.0
        runtime_pos_log_enable: false
        map_file_path: "/home/hesam/LOXO/src/FAST_LIO_ROS2/PCD/kitti_loxo_tunnel_before_first turn.pcd"

        common:
            lid_topic: "/merged_cloud"
            imu_topic: "/gps_imu/imu"
            time_sync_en: false
            time_offset_lidar_to_imu: 0.0

        preprocess:
            lidar_type: 0              
            scan_line: 10                  
            scan_rate: 10                 
            timestamp_unit: 2             
            blind: 2.0                    


        mapping:
            acc_cov: 0.01
            gyr_cov: 0.001
            b_acc_cov: 0.0001
            b_gyr_cov: 0.00001
            fov_degree: 360.0
            det_range: 100.0
            extrinsic_est_en: false
            extrinsic_T: [ 0.275, 0.0, 1.825 ]
            extrinsic_R: [ 1.0, 0.0, 0.0,
                        0.0, -1.0, 0.0,
                        0.0, 0.0, -1.0 ]


        publish:
            path_en: false
            scan_publish_en: false
            dense_publish_en: false
            scan_bodyframe_pub_en: false
            map_pub_en : false

        pcd_save:
            pcd_save_en: false
            interval: 2